### PR TITLE
UDP checksum function and test case

### PR DESCRIPTION
**Pull request by 1527thomas**
Created function for calculating UDP checksum which uses a pseudo header
Test case added within test_dhcp.py

### CODE REVIEW

**Comment by NickFulton98** [comment]
Great!

**Comment by antimony123** [comment]
Tested and confirmed to work.

**Comment by bmilkov** [comment]
It works!

**Comment by cjhouser** [comment]
Conforms to [RFC768](https://tools.ietf.org/html/rfc768) from what I can tell. LGTM

I didn't realize TCP, UDP, and IPv4 share the same [checksum algorithm](https://tools.ietf.org/html/rfc1071) (IP_checksum function in dhcp.py.) Very cool!

**Pull request merged**
